name: NordIQuEst-HPC module CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Run tests
        run: ./test/bats/bin/bats test/test.bats
